version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - npm ci

  build:
    commands:
      - npm run build

  post_build:
    commands:
      - echo "✔ Verificando existencia de .next/static..."
      - |
        if [ ! -d ".next/static" ]; then
          echo "❌ ERROR: .next/static no encontrado, abortando build."
          exit 1
        fi
      - echo "✔ .next/static encontrado"
      - echo "✅ Build completed"

artifacts:
  base-directory: .
  files:
    - '.next/**/*'         
    - 'public/**'
    - 'package.json'
    - 'package-lock.json'
    - 'next.config.js'
  exclude:
    - '**/*.md'
    - 'docs/**'
    - 'diagrams/**'
    - 'node_modules/**'

