version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - npm ci
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo "✅ Build completed"

artifacts:
  # Empacamos solo lo imprescindible
  base-directory: . 
  files:
    - '.next/**'
    - 'public/**'
    - 'next.config.js'
    - 'package.json'
    - 'package-lock.json'
  # Excluimos diagramas, docs, markdowns y node_modules
  exclude:
    - '*.md'
    - 'docs/**'
    - 'diagrams/**'
    - 'node_modules/**'
